[build]
builder = "NIXPACKS"
buildCommand = "cd client && npm ci && npm run build && cd .. && mkdir -p public && cp -r client/build/* public/"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"

[env]
NODE_ENV = "production"